#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ssh_root "description" <<'SCRIPT' ... SCRIPT — run a heredoc script on the
# droplet as root over SSH, using the initial root credential (password or
# provider-injected key). Aborts the wizard on failure (set -e), since a half
# -provisioned box needs a human to look at it, not silent continuation.
ssh_root() {
  say "$1"
  ssh -o StrictHostKeyChecking=accept-new "root@${DROPLET_IP}" 'bash -s'
}

# ssh_deploy "description" <<'SCRIPT' ... SCRIPT — same, but as the deploy
# user, authenticating with the freshly-generated deploy key.
ssh_deploy() {
  say "$1"
  ssh -o StrictHostKeyChecking=accept-new -i "${DEPLOY_KEY_PATH}" "deploy@${DROPLET_IP}" 'bash -s'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=9

banner "Provision & harden jira-clone-ui's VPS (issue #2)"
note "Run this from inside the jira-clone-ui repo checkout so 'gh secret set' targets the right repo."

# ── Stage 1: create the droplet (human-only — web dashboard, payment) ─────
stage "Create the droplet"
say "This part only you can do — it's your DigitalOcean account and your card."
open_url "https://cloud.digitalocean.com/droplets/new"
step "Image: Ubuntu 24.04 (LTS) x64"
step "Plan: Basic → Regular → the \$6/mo tier (1 GB RAM / 25 GB SSD)"
step "Datacenter region: whichever is closest to you"
step "Authentication: add your existing SSH public key if you have one, or choose a password — either works, we only use it once, for the very first login below"
step "Hostname: something like jira-clone-vps (fine to reuse this box for other projects later)"
step "Click 'Create Droplet' and wait for it to boot — then copy its public IPv4 address"
ask DROPLET_IP "Droplet public IP:"
write_env DROPLET_IP "$DROPLET_IP"

# ── Stage 2: deploy SSH keypair ────────────────────────────────────────────
stage "Deploy SSH keypair"
say "We'll generate a dedicated keypair for the 'deploy' user — separate from your personal key, so it can be rotated or revoked independently."
DEPLOY_KEY_PATH="./deploy_key"
if [[ -f "$DEPLOY_KEY_PATH" ]]; then
  note "found an existing $DEPLOY_KEY_PATH from a previous run — reusing it"
else
  ssh-keygen -t ed25519 -f "$DEPLOY_KEY_PATH" -N "" -C "deploy@jira-clone-ui" -q
  note "generated $DEPLOY_KEY_PATH (private) and ${DEPLOY_KEY_PATH}.pub (public)"
fi
write_env DEPLOY_KEY_PATH "$DEPLOY_KEY_PATH"

# ── Stage 3: create the non-root deploy user ───────────────────────────────
stage "Create the non-root 'deploy' user"
say "Logging in as root@${DROPLET_IP} to create a restricted 'deploy' user and install its public key."
warn "You'll be prompted for the root password or key you set when creating the droplet — that's expected, it's the last time root needs it interactively."
DEPLOY_PUBKEY="$(cat "${DEPLOY_KEY_PATH}.pub")"
ssh_root "Creating deploy user and installing its key..." <<SCRIPT
set -e
id -u deploy >/dev/null 2>&1 || adduser --disabled-password --gecos "" deploy
mkdir -p /home/deploy/.ssh
chmod 700 /home/deploy/.ssh
echo "${DEPLOY_PUBKEY}" > /home/deploy/.ssh/authorized_keys
chmod 600 /home/deploy/.ssh/authorized_keys
chown -R deploy:deploy /home/deploy/.ssh
echo "deploy user ready"
SCRIPT
note "verifying the deploy user can log in with its key..."
if ssh -o StrictHostKeyChecking=accept-new -i "$DEPLOY_KEY_PATH" "deploy@${DROPLET_IP}" whoami | grep -q '^deploy$'; then
  note "✓ deploy@${DROPLET_IP} login confirmed"
else
  warn "could not confirm deploy user login — stop and investigate before continuing (do NOT lock down root in stage 8 until this works)"
fi

# ── Stage 4: firewall ───────────────────────────────────────────────────────
stage "Firewall (ufw)"
ask APP_PORT "Port this app will be served on [8081]:"
APP_PORT="${APP_PORT:-8081}"
write_env APP_PORT "$APP_PORT"
ssh_root "Installing and enabling ufw..." <<SCRIPT
set -e
apt-get update -qq
apt-get install -y -qq ufw
ufw default deny incoming
ufw default allow outgoing
ufw allow 22/tcp
ufw allow ${APP_PORT}/tcp
ufw --force enable
ufw status verbose
SCRIPT

# ── Stage 5: fail2ban ───────────────────────────────────────────────────────
stage "Brute-force protection (fail2ban)"
ssh_root "Installing and enabling fail2ban for sshd..." <<'SCRIPT'
set -e
apt-get install -y -qq fail2ban
cat > /etc/fail2ban/jail.local <<'JAIL'
[sshd]
enabled = true
JAIL
systemctl enable --now fail2ban
systemctl is-active fail2ban
SCRIPT

# ── Stage 6: nginx ──────────────────────────────────────────────────────────
stage "Web server (nginx)"
ssh_root "Installing nginx..." <<'SCRIPT'
set -e
apt-get install -y -qq nginx
systemctl enable --now nginx
SCRIPT

# ── Stage 7: release directory, placeholder, nginx server block ────────────
stage "Release directory, placeholder page, nginx site"
say "Setting up /srv/jira-clone-ui/releases/ + a 'current' symlink, matching ADR-0001's atomic-release layout, and a placeholder page so there's something to verify before the first real deploy exists."
ssh_root "Creating release skeleton and nginx server block..." <<SCRIPT
set -e
APP_DIR=/srv/jira-clone-ui
TS=\$(date +%Y%m%d%H%M%S)
mkdir -p "\${APP_DIR}/releases/\${TS}"
cat > "\${APP_DIR}/releases/\${TS}/index.html" <<'HTML'
<!doctype html>
<title>jira-clone-ui</title>
<h1>jira-clone-ui placeholder — awaiting first deploy</h1>
HTML
ln -sfn "\${APP_DIR}/releases/\${TS}" "\${APP_DIR}/current"
chown -R deploy:deploy "\${APP_DIR}"

cat > /etc/nginx/sites-available/jira-clone-ui <<NGINX
server {
    listen ${APP_PORT};
    server_name _;
    root \${APP_DIR}/current;
    index index.html;
    location / {
        try_files \\\$uri \\\$uri/ /index.html;
    }
}
NGINX
ln -sf /etc/nginx/sites-available/jira-clone-ui /etc/nginx/sites-enabled/jira-clone-ui
nginx -t
systemctl reload nginx
echo "nginx site enabled on port ${APP_PORT}"
SCRIPT

# ── Stage 8: verify ─────────────────────────────────────────────────────────
stage "Verify the placeholder is live"
say "Checking http://${DROPLET_IP}:${APP_PORT}/ ..."
if command -v curl >/dev/null 2>&1 && curl -fsS "http://${DROPLET_IP}:${APP_PORT}/" | grep -q "jira-clone-ui"; then
  note "✓ placeholder page served correctly"
else
  warn "couldn't verify automatically — open http://${DROPLET_IP}:${APP_PORT}/ in a browser and confirm you see the placeholder page before continuing"
  pause "Press Enter once you've confirmed it manually"
fi

if confirm "Deploy user confirmed working and placeholder verified — lock down root SSH login + password auth now?"; then
  ssh_root "Disabling root login and password authentication..." <<'SCRIPT'
set -e
sed -i 's/^#\?PermitRootLogin.*/PermitRootLogin no/' /etc/ssh/sshd_config
sed -i 's/^#\?PasswordAuthentication.*/PasswordAuthentication no/' /etc/ssh/sshd_config
systemctl restart sshd
echo "root login and password auth disabled"
SCRIPT
  note "confirming root login is now actually rejected..."
  if ssh -o BatchMode=yes -o ConnectTimeout=5 -o StrictHostKeyChecking=accept-new "root@${DROPLET_IP}" true >/dev/null 2>&1; then
    warn "root login still succeeded after the lockdown — sshd_config may not have matched on this image; check it by hand"
    SKIPPED+=("Verify root SSH login is actually rejected — the sed edit may not have matched /etc/ssh/sshd_config on this image")
  else
    note "✓ root login now rejected"
  fi
  if ssh -o BatchMode=yes -o ConnectTimeout=5 -i "$DEPLOY_KEY_PATH" "deploy@${DROPLET_IP}" whoami >/dev/null 2>&1; then
    note "✓ deploy user login still works after the restart"
  else
    warn "deploy user login failed after the sshd restart — you may be locked out of the box; investigate via your provider's web console"
  fi
else
  SKIPPED+=("Disable root SSH login + password auth (re-run this wizard, or do it by hand, once you're confident the deploy user works)")
  warn "left root login enabled — re-run this wizard later to lock it down"
fi

# ── Stage 9: GitHub Actions secrets ─────────────────────────────────────────
stage "Store GitHub Actions secrets"
say "This writes DEPLOY_HOST, DEPLOY_SSH_KEY, and DEPLOY_PORT as secrets on the current repo, for the deploy workflow (issue #4) to use."
if confirm "Write these 3 secrets to this repo's GitHub Actions now?"; then
  set_secret DEPLOY_HOST "$DROPLET_IP"
  set_secret DEPLOY_SSH_KEY "$(cat "$DEPLOY_KEY_PATH")"
  set_secret DEPLOY_PORT "$APP_PORT"
else
  SKIPPED+=("GitHub secrets DEPLOY_HOST, DEPLOY_SSH_KEY, DEPLOY_PORT — set by hand with 'gh secret set' when ready")
fi

finish

note "Acceptance checklist (issue #2):"
note "  [ ] http://${DROPLET_IP}:${APP_PORT}/ returns the placeholder page — checked in Stage 8"
note "  [ ] deploy@${DROPLET_IP} works via key; root login + password auth rejected — checked in Stage 8"
note "  [ ] 'ufw status' shows default-deny + allows for 22 and ${APP_PORT}; fail2ban is running — printed live in Stage 4/5 output above"
note "  [ ] DEPLOY_HOST, DEPLOY_SSH_KEY, DEPLOY_PORT are set as GitHub Actions secrets"
note "(root SSH access is now locked down and 'deploy' has no sudo rights, so ufw/fail2ban can't be re-queried remotely from here — use your provider's web console if you ever need to recheck them)"
warn "Keep ./deploy_key and ./deploy_key.pub — they're gitignored, but back the private key up somewhere safe (it's the only copy)."
